### PR TITLE
chore: add continuous deployment

### PR DESCRIPTION
**Pull request by Rishabhltfb**
Add continuous deployment for Firestore security rules.

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Do this in CI, this will deploy the rules regardless of tests passing or failing

**Comment by Rishabhltfb** [comment]
@iamareebjamal  I have made the required changes, please have a look.

**Comment by iamareebjamal** [comment]
There's a very simple solution. Just place the deployment step below tests and run it on master branch. I'll link an example

**Comment by Rishabhltfb** [comment]
@iamareebjamal, is this way correct?

**Pull request merged**
